from __future__ import annotations

import os
import subprocess
import uuid
from pathlib import Path

from kitsune.domain.models import LaunchPlan, LaunchRequest, LaunchResult

try:
    import minecraft_launcher_lib
    from minecraft_launcher_lib import command, utils
except Exception:
    minecraft_launcher_lib = None


def get_offline_uuid(username: str) -> str:
    """Generate offline UUID for demo/offline player."""
    return str(uuid.uuid3(uuid.NAMESPACE_DNS, "OfflinePlayer:" + username))


class MinecraftLauncherRuntime:
    def __init__(self) -> None:
        self._processes: dict[int, subprocess.Popen[str]] = {}

    def build_plan(self, request: LaunchRequest) -> LaunchPlan:
        """Build a launch plan with command preview and launcher options."""
        launcher_options = {
            "username": request.username,
            "uuid": get_offline_uuid(request.username),
            "demo": False,
            "token": "",
            "jvmArguments": [
                f"-Xmx{request.ram_gb}G",
                f"-Xms{request.ram_gb}G",
                "--enable-native-access=ALL-UNNAMED",
                *request.extra_jvm_args,
            ],
            "launcherName": "Kitsune",
            "launcherVersion": "0.1",
            "gameDirectory": str(request.minecraft_path),
            "nativesDirectory": str(request.minecraft_path),
        }

        if request.java_path:
            launcher_options["executablePath"] = request.java_path

        # Generate command preview
        if minecraft_launcher_lib:
            try:
                preview_cmd = command.get_minecraft_command(
                    request.version, request.minecraft_path, launcher_options
                )
                command_preview = preview_cmd[:5] + ["..."]
            except Exception:
                command_preview = ["<unable to preview>"]
        else:
            command_preview = ["<launcher lib unavailable>"]

        notes = [
            "Preview command shown for diagnostics.",
            "Actual launch command is generated by minecraft-launcher-lib.",
        ]

        return LaunchPlan(
            version=request.version,
            install_required=not request.is_version_installed,
            command_preview=command_preview,
            launcher_options=launcher_options,
            notes=notes,
        )

    def start(self, plan: LaunchPlan) -> LaunchResult:
        """Execute the Minecraft launch command."""
        if minecraft_launcher_lib is None:
            return LaunchResult(
                started=False,
                pid=None,
                message="minecraft-launcher-lib is unavailable in the current environment.",
            )

        try:
            version = plan.version
            minecraft_path = plan.launcher_options.get("gameDirectory")

            if not minecraft_path:
                return LaunchResult(
                    started=False,
                    pid=None,
                    message="Game directory not specified in launch options.",
                )

            # Build the full command
            minecraft_command = command.get_minecraft_command(version, minecraft_path, plan.launcher_options)

            # Clean up unwanted arguments (platform-specific)
            minecraft_command = self._clean_command(minecraft_command)
            minecraft_command += ["--accessToken", "0", "--userType", "legacy"]

            # Platform-specific process flags
            creation_flags = 0
            if subprocess.os.name == "nt":  # Windows
                creation_flags = subprocess.CREATE_NO_WINDOW | subprocess.HIGH_PRIORITY_CLASS

            # Launch the process
            proc = subprocess.Popen(
                minecraft_command,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                cwd=minecraft_path,
                creationflags=creation_flags,
            )

            self._processes[proc.pid] = proc

            return LaunchResult(
                started=True,
                pid=proc.pid,
                message=f"Minecraft process started with PID {proc.pid}.",
            )

        except FileNotFoundError as exc:
            return LaunchResult(
                started=False,
                pid=None,
                message=f"Java executable or Minecraft file not found: {exc}",
            )
        except Exception as exc:
            return LaunchResult(
                started=False,
                pid=None,
                message=f"Failed to start Minecraft: {exc}",
            )

    def is_running(self, pid: int | None) -> bool:
        if pid is None:
            return False

        process = self._processes.get(pid)
        if process is not None:
            return process.poll() is None

        try:
            os.kill(pid, 0)
            return True
        except OSError:
            return False

    @staticmethod
    def _clean_command(cmd: list[str]) -> list[str]:
        """Remove unwanted arguments from command (platform-specific or development args)."""
        filters = {
            "-XstartOnFirstThread",  # macOS specific, can conflict
            "--demo",
            "--accessToken",
            "--userType",
            "msa",
            "",
        }
        return [x for x in cmd if x not in filters]

    def get_available_versions(self) -> list[dict]:
        """Fetch list of available Minecraft versions from the manifest."""
        if minecraft_launcher_lib is None:
            return []

        try:
            manifest = utils.get_version_list()
            return [
                {
                    "id": v["id"],
                    "type": v["type"],
                    "releaseTime": v.get("releaseTime"),
                    "installed": False,
                }
                for v in manifest
            ]
        except Exception:
            return []

    def get_installed_versions(self, minecraft_path: str) -> list[dict]:
        """Get list of installed Minecraft versions."""
        if minecraft_launcher_lib is None:
            return []

        try:
            installed = utils.get_installed_versions(minecraft_path)
            return [
                {
                    "id": v["id"],
                    "type": v["type"],
                    "installed": True,
                }
                for v in installed
            ]
        except Exception:
            return []

    def download_version(self, version: str, minecraft_path: str) -> dict:
        """Download and install a Minecraft version."""
        if minecraft_launcher_lib is None:
            return {"success": False, "message": "minecraft-launcher-lib not available"}

        try:
            utils.download_version(version, minecraft_path)
            return {"success": True, "message": f"Version {version} downloaded successfully"}
        except Exception as exc:
            return {"success": False, "message": f"Failed to download version: {exc}"}


def default_minecraft_path() -> str:
    home = Path.home()
    return str(home / ".minecraft")
